Syclass\FipeBundle\Entity\FipeVehiclePrice:
    type: entity
    table: oc_t_fipe_vehicle_price
    repositoryClass: Syclass\FipeBundle\Repository\FipeVehiclePriceRepository
    id:
        id:
            type: string
            scale: 0
            length: 40
            unique: false
            nullable: false
            precision: 0
            id: true
    fields:
        price:
            type: decimal
            scale: 2
            length: null
            unique: false
            nullable: false
            precision: 0
        slug:
            type: string
            scale: 0
            length: 60
            unique: false
            nullable: false
            precision: 0
        updated:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        inserted:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        table:
            targetEntity: Syclass\FipeBundle\Entity\FipeTable
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: prices
            joinColumns:
                table_id:
                    referencedColumnName: id
            orphanRemoval: false
        vehicle:
            targetEntity: Syclass\FipeBundle\Entity\FipeVehicle
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: prices
            joinColumns:
                vehicle_id:
                    referencedColumnName: id
            orphanRemoval: false
        manufacturer:
            targetEntity: Syclass\FipeBundle\Entity\FipeManufacturer
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: vehicles
            joinColumns:
                manufacturer_id:
                    referencedColumnName: id
            orphanRemoval: false
        year:
            targetEntity: Syclass\FipeBundle\Entity\FipeVehicleYear
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: prices
            joinColumns:
                year_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
