Syclass\FipeBundle\Entity\FipeVehicleUpdate:
    type: entity
    table: oc_t_fipe_vehicle_update
    id:
        id:
            type: string
            scale: 0
            length: 40
            unique: false
            nullable: false
            precision: 0
            id: true
    fields:
        updated:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        inserted:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        table:
            targetEntity: Syclass\FipeBundle\Entity\FipeTable
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: vehicle_updates
            joinColumns:
                table_id:
                    referencedColumnName: id
            orphanRemoval: false
        vehicle:
            targetEntity: Syclass\FipeBundle\Entity\FipeVehicle
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: updates
            joinColumns:
                vehicle_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
